apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-services
  labels:
    app: my-services
spec:
  replicas: 2
  template:
    metadata:
      name: my-services
      labels:
        app: my-services
    spec:
      containers:
      - name: service1
        image: rlcontainertest.azurecr.io/service1:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5001
      nodeSelector:
        "kubernetes.io/os": linux
      imagePullSecrets:
      - name: azure-secret
  selector:
    matchLabels:
      app: my-services
---
apiVersion: v1
kind: Service
metadata:
  name: services-svc
spec:
  selector:
    app: my-services
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 8080
    name: http
  type: NodePort
