apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service1
  labels:
    app: my-service1
spec:
  replicas: 2
  template:
    metadata:
      name: my-service1
      labels:
        app: my-service1
    spec:
      containers:
      - name: service1
        image: <serviceA_image>
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      nodeSelector:
        "kubernetes.io/os": linux
      imagePullSecrets:
      - name: <azure-secret>
  selector:
    matchLabels:
      app: my-service1
---
apiVersion: v1
kind: Service
metadata:
  name: service1-svc
spec:
  selector:
    app: my-service1
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 80
    name: http
